### ISSUE TITLE
On some answers, images doesn't load.

### ISSUE THREAD

**Issue by Roy404Dev** [naglissul/vbe-sort#9]
![img1](https://github.com/naglissul/vbe-sort/assets/109029329/59cc398a-40f3-4668-bbd4-83629bb758d4)
![img2](https://github.com/naglissul/vbe-sort/assets/109029329/afe773ea-fcdf-4e17-bfce-3125efb81442)

**Comment by naglissul** [comment]
Ah, yes, one day gonna fix that

**Comment by naglissul** [comment]
fixed :) now it only shows the "Atsakymas" Accordion, when there is an aswer screenshot. Thx for observation!
